##====================================================

# This is a collection of functions that will create
# a matrix with associated mutator and accessor functions
# that can cache and caluculate the multiplicative inverse 
# of a square invertible matrix.

# Created for assignment 2 for the R Programming Course

##====================================================



## 
# This function uses the provided, unchanged signature from 
# rdpeng's ProgrammingAssignment2 repository.
#
# It assumes a square invertible matrix as input 
# and returns a list that includes getter and setter
# functions for the provided matrix and its inverse.
##
makeCacheMatrix <- function(x = matrix()) {
  #inverse of the provided square matrix
  inverse <- NULL
  #used to store a matrix
  set <- function(y) {
    x <<- y
    #everytime the matrix is created or changed 
    #the inverse is set to NULL so it must be recalculated
    inverse <<- NULL
  } #end of set
  #used to retrieve stored matrix
  getMatrix <- function() x
  #used to cache multiplicative inverse
  #of the stored matrix
  setInverse <- function(i) inverse <<- i
  #used to retrive the cached inverse of the 
  #stored matrix
  getInverse <- function() inverse
  #return list of functions for setting/getting
  #the stored matrix and its inverse
  list(
    set = set, 
    getMatrix = getMatrix,
    setInverse = setInverse,
    getInverse = getInverse
  ) #end of returned list
} #end of makeCacheMatrix function



## 
# This function uses the provided, unchanged signature from 
# rdpeng's ProgrammingAssignment2 repository.
#
# It assumes a list generated by the makeCacheMatrix function 
# as input and returns the mulitiplicative inverse of 
# the matrix stored in [List_Name]$getMatrix.  
# The inverse will either be calculated if it hasn't been done
# already or pulled from the cache.  If it is pulled from
# the cache then a message will be alert the user of this.
##
cacheSolve <- function(x, ...) {
  #get the cached inverse of the matrix
  i <- x$getInverse()
  #test if the inverse has already been calculated
  # and calculate if needed
  if(!is.null(i)) {
    message("getting cached data")
  } else {
    i <- solve(x$getMatrix(), ...)
    x$setInverse(i)
  } #end of else
  #return the inverse of the stored matrix
  i
} #end of cacheSolve
